### ISSUE TITLE
Can't start the app.js

### ISSUE THREAD

**Issue by MatteoGauthier** [atinux/LiveChat#1]
Bonjour voici le stdout après l’exécution de la commande `node app.js`
```
Mattaio@DESKTOP-1TK6TKC MINGW64 .../Tests/LiveChat (master)
$ node app.js
D:\WorkFolder\Devlopment\Tests\LiveChat\node_modules\socket.io-client\lib\util.js:248
    util.merge(ctor.prototype, ctor2.prototype);
                                     ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.util.mixin (D:\WorkFolder\Devlopment\Tests\LiveChat\node_modules\socket.io-client\lib\util.js:248:38)
    at D:\WorkFolder\Devlopment\Tests\LiveChat\node_modules\socket.io-client\lib\namespace.js:35:11
    at Object.<anonymous> (D:\WorkFolder\Devlopment\Tests\LiveChat\node_modules\socket.io-client\lib\namespace.js:239:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```
Avez-vous une solution ?

**Comment by atinux** [comment]
Bonjour,

Je suis désolé mais ce repo n'est plus maintenu.

**Comment by MatteoGauthier** [comment]
Dommage merci
